version: '3.7'
services:
  ztsfc_pep:
    image: vs-uulm/ztsfc_http_pep:latest
    restart: unless-stopped
    ports:
      - "192.168.178.2:443:443"
    volumes:
      - "./ztsfc_http_pep/config/conf.yml:/config/conf.yml:ro"
      - "./ztsfc_http_pep/certs/:/certs/:ro"
      - "./ztsfc_http_pep/blocklists/:/blocklists/:ro"
      - "/etc/letsencrypt/live/cosca-admin.informatik.uni-ulm.de/:/etc/letsencrypt/live/cosca-admin.informatik.uni-ulm.de/:ro"
      - "/etc/letsencrypt/archive/cosca-admin.informatik.uni-ulm.de/:/etc/letsencrypt/archive/cosca-admin.informatik.uni-ulm.de/:ro"
    depends_on:
      - "ztsfc_ldap"
    networks:
      ztsfc_network:
        aliases:
          - pep.ztsfc.com

  ztsfc_ldap:
    image: osixia/openldap:1.5.0
    hostname: "ldap.ztsfc.com"
    environment:
      LDAP_LOG_LEVEL: "256"
      LDAP_ORGANISATION: "ZTSFC"
      LDAP_DOMAIN: "ztsfc.com"
      LDAP_BASE_DN: "dc=ztsfc,dc=com"
      LDAP_ADMIN_PASSWORD_FILE: /run/secrets/admin_pw
      LDAP_CONFIG_PASSWORD_FILE: /run/secrets/config_pw
      LDAP_READONLY_USER: "true"
      LDAP_READONLY_USER_USERNAME: "readonly"
      #LDAP_READONLY_USER_PASSWORD: "onlyread"
      LDAP_READONLY_USER_PASSWORD_FILE: /run/secrets/readonly_pw
      LDAP_TLS: "true"
      LDAP_TLS_CRT_FILENAME: "ldap.crt"
      LDAP_TLS_KEY_FILENAME: "ldap.key"
      LDAP_TLS_DH_PARAM_FILENAME: "dhparam.pem"
      LDAP_TLS_CA_CRT_FILENAME: "ca.crt"
      LDAP_TLS_ENFORCE: "true"
      LDAP_TLS_CIPHER_SUITE: "SECURE256:-VERS-TLS-ALL:+VERS-TLS1.3"
      LDAP_TLS_VERIFY_CLIENT: "never"
    command: "--loglevel debug --copy-service"
    volumes:
      - "./ztsfc_http_ldap/ldap_var_lib_ldap:/var/lib/ldap"
      - "./ztsfc_http_ldap/ldap_etc_ldap_slapdd:/etc/ldap/slapd.d"
      - "./ztsfc_http_ldap/certs/:/container/service/slapd/assets/certs/"
      - "./ztsfc_http_ldap/bootstrap.ldif:/container/service/slapd/assets/config/bootstrap/ldif/custom/bootstrap.ldif"
    secrets:
      - admin_pw
      - config_pw
      - readonly_pw
    networks:
      ztsfc_network:
        aliases:
          - ldap.ztsfc.com

  ztsfc_pdp:
    image: vs-uulm/ztsfc_http_pdp:latest
    volumes:
      - "./ztsfc_http_pdp/certs/:/certs/:ro"
      - "./ztsfc_http_pdp/config/conf.yml:/config/conf.yml:ro"
      - "./ztsfc_http_pdp/policies/policies.yml:/policies/policies.yml:ro"
    networks:
      ztsfc_network:
        aliases:
          - pdp.ztsfc.com

  ztsfc_pip:
    image: vs-uulm/ztsfc_http_pip:latest
    ports:
      - "192.168.178.2:8080:8080"
    volumes:
      - "./ztsfc_http_pip/certs/:/certs/:ro"
      - "./ztsfc_http_pip/config/conf.yml:/config/conf.yml:ro"
    networks:
      ztsfc_network:
        aliases:
          - pip.ztsfc.com

  ztsfc_sfp_logic:
    image: vs-uulm/ztsfc_http_sfp_logic:latest
    volumes:
      - "./ztsfc_http_sfp_logic/certs/:/certs/:ro"
      - "./ztsfc_http_sfp_logic/config/conf.yml:/config/conf.yml:ro"
      - "./ztsfc_http_sfp_logic/policies/policies.yml:/policies/policies.yml:ro"
    networks:
      ztsfc_network:
        aliases:
          - sfpl.ztsfc.com

  ztsfc_sf_logger:
    image: vs-uulm/ztsfc_http_sf_logger:latest
    volumes:
      - "./ztsfc_http_sf_logger/certs/:/certs/:ro"
      - "./ztsfc_http_sf_logger/config/conf.yml:/config/conf.yml:ro"
    networks:
      ztsfc_network:
        aliases:
          - sf_logger.ztsfc.com

  ztsfc_sf_ips:
    image: vs-uulm/ztsfc_http_sf_ips:latest
    volumes:
      - "./ztsfc_http_sf_ips/certs/:/certs/:ro"
      - "./ztsfc_http_sf_ips/config/conf.yml:/config/conf.yml:ro"
    networks:
      ztsfc_network:
        aliases:
          - ips.ztsfc.com

  ztsfc_service:
    image: vs-uulm/ztsfc_http_service:latest
    volumes:
      - "./ztsfc_http_service/config/conf.yml:/config/conf.yml:ro"
      - "./ztsfc_http_service/certs/:/certs/:ro"
      - "/etc/letsencrypt/live/service.ztsfc.com/:/etc/letsencrypt/live/service.ztsfc.com/:ro"
      - "/etc/letsencrypt/archive/service.ztsfc.com:/etc/letsencrypt/archive/service.ztsfc.com/:ro"
    networks:
      ztsfc_network:
        aliases:
          - service.ztsfc.com

  ztsfc_loki:
    image: grafana/loki:latest
    hostname: loki.ztsfc.com
    container_name: ztsfc_loki
    restart: unless-stopped
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    volumes:
      - "./ztsfc_http_loki/loki:/loki"
      - "./ztsfc_http_loki/loki-config.yml:/etc/loki/local-config.yaml:ro"
    networks:
      ztsfc_network:
        aliases:
          - loki.ztsfc.com

  ztsfc_grafana:
    image: grafana/grafana:latest
    hostname: grafana.ztsfc.com
    container_name: ztsfc_grafana
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - "./ztsfc_http_grafana/var_lib_grafana/:/var/lib/grafana/"
      - "./ztsfc_http_grafana/certs/:/etc/certs/"
      - "./ztsfc_http_grafana/grafana.ini/:/etc/grafana/grafana.ini:ro"
    networks:
      ztsfc_network:
        aliases:
          - grafana.ztsfc.com

secrets:
  admin_pw:
    file: ztsfc_http_ldap/secrets/admin_pw.txt
  config_pw:
    file: ztsfc_http_ldap/secrets/config_pw.txt
  readonly_pw:
    file: ztsfc_http_ldap/secrets/readonly_pw.txt

networks:
  ztsfc_network:
    driver: bridge
