system_logger:
  system_logger_logging_level: debug
  system_logger_destination: stdout
  system_logger_format: text

pdp:
  listen_addr: "pdp.ztsfc.com:443"
  certs_pdp_accepts_when_shown_by_pep:
    - ./certs/ca.crt
  cert_shown_by_pdp_to_pep: ./certs/pdp.crt
  privkey_for_cert_shown_by_pdp_to_pep: ./certs/pdp.key
  logging_hook:
    hook_url: "http://loki.ztsfc.com:3100/loki/api/v1/push"
    cert_shown_by_pdp_to_hook: ./certs/pdp.crt
    privkey_for_cert_shown_by_pdp_to_hook: ./certs/pdp.key
    certs_pdp_accepts_when_shown_by_hook:
      - ./certs/ca.crt

pip:
  target_addr: "https://pip.ztsfc.com:443"
  device_endpoint: "/get-device-attributes"
  update_device_endpoint: "/update-device-attributes"
  system_endpoint: "/get-system-attributes"
  certs_pdp_accepts_when_shown_by_pip:
    - ./certs/ca.crt
  cert_shown_by_pdp_to_pip: ./certs/pdp.crt
  privkey_for_cert_shown_by_pdp_to_pip: ./certs/pdp.key
