system_logger:
  system_logger_logging_level: debug
  system_logger_destination: stdout
  system_logger_format: text

service:
  listen_addr: "service.ztsfc.com:443"
  cert_shown_by_service_to_clients: ./certs/service_example.crt
  privkey_for_cert_shown_by_service_to_clients: ./certs/service_example_priv.key
  cert_service_accepts: ./certs/CA_root.crt
  mode: pep
  file: false
