sni: service1.testbed.informatik.uni-ulm.de
listen_addr: ":443"
certs_service_accepts_when_presented_by_ext: 
  - ./certs/bwnet_root.crt
certs_service_accepts_when_presented_by_int:
  - ./certs/bwnet_root.crt
cert_presented_by_service_to_ext_matching_sni: /etc/letsencrypt/live/service1.testbed.informatik.uni-ulm.de/fullchain.pem
privkey_for_cert_presented_by_service_to_ext: /etc/letsencrypt/live/service1.testbed.informatik.uni-ulm.de/privkey.pem
cert_presented_by_service_to_int: ./certs/server.crt
privkey_for_cert_presented_by_service_to_int: ./certs/private.key
